# 1단계: 빌드
FROM node:20-alpine AS builder
WORKDIR /app

# pnpm 준비
RUN corepack enable && corepack prepare pnpm@9.12.2 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# 🔥 GitHub Actions에서 build-arg로 전달받을 모든 NEXT_PUBLIC_* 값 추가
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_GRAFANA_EKS_URL
ENV NEXT_PUBLIC_GRAFANA_EKS_URL=$NEXT_PUBLIC_GRAFANA_EKS_URL

ARG NEXT_PUBLIC_GRAFANA_ALB_URL
ENV NEXT_PUBLIC_GRAFANA_ALB_URL=$NEXT_PUBLIC_GRAFANA_ALB_URL

ARG NEXT_PUBLIC_GRAFANA_RDS_URL
ENV NEXT_PUBLIC_GRAFANA_RDS_URL=$NEXT_PUBLIC_GRAFANA_RDS_URL

ARG NEXT_PUBLIC_GRAFANA_VPN_URL
ENV NEXT_PUBLIC_GRAFANA_VPN_URL=$NEXT_PUBLIC_GRAFANA_VPN_URL

ARG NEXT_PUBLIC_GRAFANA_NAT_URL
ENV NEXT_PUBLIC_GRAFANA_NAT_URL=$NEXT_PUBLIC_GRAFANA_NAT_URL

ARG NEXT_PUBLIC_GRAFANA_S3_URL
ENV NEXT_PUBLIC_GRAFANA_S3_URL=$NEXT_PUBLIC_GRAFANA_S3_URL

ARG NEXT_PUBLIC_GRAFANA_SENSITIVE_DB_URL
ENV NEXT_PUBLIC_GRAFANA_SENSITIVE_DB_URL=$NEXT_PUBLIC_GRAFANA_SENSITIVE_DB_URL

ARG NEXT_PUBLIC_GRAFANA_RPC_URL
ENV NEXT_PUBLIC_GRAFANA_RPC_URL=$NEXT_PUBLIC_GRAFANA_RPC_URL

ARG NEXT_PUBLIC_GRAFANA_BLOCKCHAIN_VALIDATE_URL
ENV NEXT_PUBLIC_GRAFANA_BLOCKCHAIN_VALIDATE_URL=$NEXT_PUBLIC_GRAFANA_BLOCKCHAIN_VALIDATE_URL

ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

COPY . .
RUN pnpm build

# 2단계: 실행
FROM node:20-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.12.2 --activate
ENV NODE_ENV=production

COPY --from=builder /app ./

EXPOSE 3000
CMD ["pnpm", "start"]
